import PropTypes from 'prop-types';

export default {
  propTypes: {
    // alignmentBaseline: PropTypes.string,
    // baselineShift: PropTypes.string,
    // clip: PropTypes.string,
    // clipPath: PropTypes.string,
    // clipRule: PropTypes.string,
    // color: PropTypes.string,
    // colorInterpolation: PropTypes.string,
    // colorInterpolationFilters: PropTypes.string,
    // colorProfile: PropTypes.string,
    // colorRendering: PropTypes.string,
    // cursor: PropTypes.string,
    // direction: PropTypes.string,
    // display: PropTypes.string,
    // dominantBaseline: PropTypes.string,
    // enableBackground: PropTypes.string,
    fill: PropTypes.string,
    // fillOpacity: PropTypes.string,
    // fillRule: PropTypes.string,
    // filter: PropTypes.string,
    // floodColor: PropTypes.string,
    // floodOpacity: PropTypes.string,
    // fontFamily: PropTypes.string,
    // fontSize: PropTypes.string,
    // fontSizeAdjust: PropTypes.string,
    // fontStretch: PropTypes.string,
    // fontStyle: PropTypes.string,
    // fontVariant: PropTypes.string,
    // fontWeight: PropTypes.string,
    // glyphOrientationHorizontal: PropTypes.string,
    // glyphOrientationVertical: PropTypes.string,
    // imageRendering: PropTypes.string,
    // kerning: PropTypes.string,
    // letterSpacing: PropTypes.string,
    // lightingColor: PropTypes.string,
    // markerEnd: PropTypes.string,
    // markerMid: PropTypes.string,
    // markerStart: PropTypes.string,
    // mask: PropTypes.string,
    // opacity: PropTypes.string,
    // overflow: PropTypes.string,
    // pointerEvents: PropTypes.string,
    // shapeRendering: PropTypes.string,
    // stopColor: PropTypes.string,
    // stopOpacity: PropTypes.string,
    stroke: PropTypes.string,
    // strokeDasharray: PropTypes.string,
    // strokeDashoffset: PropTypes.string,
    // strokeLinecap: PropTypes.string,
    // strokeLinejoin: PropTypes.string,
    // strokeMiterlimit: PropTypes.string,
    // strokeOpacity: PropTypes.string,
    // strokeWidth: PropTypes.string,
    // textAnchor: PropTypes.string,
    // textDecoration: PropTypes.string,
    // textRendering: PropTypes.string,
    // unicodeBidi: PropTypes.string,
    // visibility: PropTypes.string,
    // wordSpacing: PropTypes.string,
    // writingMode: PropTypes.string,
  },
  defaultProps: {
    fill: null,
    stroke: null,
  },
};
